Makefile
It should point to the GitHub organisation for ifupdown-ng.
=> Makefile: Update bug reporting URL

Makefile
This commit ensures that `${LIBIFUPDOWN_LIB}` is removed when `make
clean` is run.
=> Makefile: Ensure built libs are removed in `clean`

cmd/ifquery.c, cmd/ifupdown.c, cmd/multicall-options.c, cmd/multicall.h
These commits add an informative message advising people to check the manpage for more information, for example:
```
For more information: man 8 ifup
```
=> add manpage xref to applet help output

cmd/multicall.h, libifupdown/interface-file.c, libifupdown/libifupdown.h, tests/fixtures/vrf-ifupdown2.interfaces, tests/ifquery_test
Some terms used by ifupdown2 do not trigger our implicit use system, and so we have other terms for those.
Right now, this is primarily `vrf` -> `vrf-member`, but the framework allows for adding other definitions.
Also, add a fixture and tests for ifupdown2 vrf configuration.
=> add compatibility with problematic ifupdown2 terms

executor-scripts/linux/gre, tests/fixtures/gre.interfaces, tests/ifquery_test, tests/linux/Kyuafile, tests/linux/gre_test
This is an executor that allows for advanced GRE tunnel configuration using ip-link(8).  iproute2 is required to make use of this executor, it will not work with busybox.
Closes #26.
=> gre executor

executor-scripts/linux/static, libifupdown/interface-file.c, libifupdown/interface.c, libifupdown/interface.h, libifupdown/lifecycle.c, tests/fixtures/vrf.interfaces, tests/ifquery_test, tests/linux/static_test
This allows for static route installation in the designated `vrf-table` when configured.
```
iface vrf-red
vrf-table 1
gateway 1.2.3.4
```
=> vrf static route support

.github/workflows/build.yml, Makefile, executor-scripts/linux/link, executor-scripts/stub/vlan, libifupdown/interface.c, tests/fixtures/vlan-named.interfaces, tests/ifquery_test, tests/linux/link_test
Unify vlan configuration into the link executor.
Tested with iproute2 and busybox iproute.
Closes Alpine #11885.
=> unify link and vlan executors

libifupdown/execute.c, libifupdown/execute.h, libifupdown/lifecycle.c
This is helpful when using `ifup -v` to debug people's configs.
=> execute: note the phase each executor is being invoked in

executor-scripts/linux/dhcp, tests/linux/dhcp_test
BusyBox ifupdown provides the `udhcpc-opts` property to specify additional options to udhcpc.
Alpine #11905.
=> add support for udhcpc-opts

cmd/ifquery.c, cmd/ifupdown.c, cmd/multicall-exec-options.c, libifupdown/execute.h, libifupdown/interface.h, libifupdown/lifecycle.c, libifupdown/state.c, libifupdown/state.h, tests/fixtures/deferred-teardown-1.ifstate, tests/fixtures/deferred-teardown-1.interfaces, tests/fixtures/deferred-teardown-2.ifstate, tests/fixtures/deferred-teardown-2.interfaces, tests/ifdown_test
This adds refcounting to the dependency tree walker by changing `lif_state` functions to operate on `lif_state_record` objects.
Refcounting is used to track which interfaces can be safely torn down without having to compute all possible views of the dependency graph and cross-checking them.
Closes #57.
Closes #63.
Closes #46.
=> refcounting

cmd/ifquery.c, cmd/ifupdown.c, libifupdown/interface.h, libifupdown/lifecycle.c, libifupdown/lifecycle.h, tests/fixtures/teardown-dep-ordering.ifstate, tests/fixtures/teardown-dep-ordering.interfaces, tests/ifdown_test, tests/ifup_test
Color the dependency graph with reverse dependency information and use this to re-order the interface collection.
This reorders the auto interface list in such a way that the dependency solver's solution will be aligned regardless of order in the config file.
We add tests to verify that auto interfaces are appropriately skipped (due to being initialized earlier by the dependency solver).
Closes #71.
=> dependency graph: reverse-dependency coloring

Makefile, executor-scripts/linux/ethtool, libifupdown/interface-file.c, tests/linux/Kyuafile, tests/linux/ethtool_test
Allow setting ethtool properties in the `ethtool-` namespace with the `ethtool` executor.  We also remap all relevant `ifupdown2` and Debian terms to their appropriate counterparts in the `ethtool-` namespace.
Closes #53.
=> ethtool support

cmd/ifupdown.c, libifupdown/interface-file.c, libifupdown/interface.c, libifupdown/interface.h, libifupdown/lifecycle.c
Do not configure interfaces which have a configuration know to be broken.
Currently this only happens when using "inherit" to an non-existing iface
or to an iface and not a template, and having allow_any_iface_as_template
set to 0.
In those cases broken ifaces will not be configured unless ifup/ifdown is
invoked with --force.
=> ifupdown: Don't configure errornous interfaces.

executor-scripts/linux/static, tests/linux/static_test
Hetzner uses link-local addressing for their default IPv6 route,
accordingly we should specify the device a route is associated with
so that it will use the correct interface.
Thanks to Devin Brown for reporting this issue.
=> static: always associate default routes with $IFACE

Makefile, doc/interfaces-bond.scd, doc/interfaces.scd, executor-scripts/linux/bond, libifupdown/interface-file.c, libifupdown/lifecycle.c
* Add a bond executor
* Add mappings from ifupdown1/2
* Add a detailed man page
* Remove legacy compatiblity glue for setups with 'requires' only
The current implementation has to work around the fact that member interfaces
will be already up then the bond is created. This is simply done by downing
them, adding them to the bundle and upping them again. This can possible be
done in a nicer way after revisiting the ordering of plugin execution (#12).
Closes #91
=> Add support for bonding / LAGs.

doc/interfaces.scd, executor-scripts/linux/link
This adds support for veth interface pairs as referenced #85 
An example config is
```
auto veth_ext2int
iface veth_ext2int
link-type veth
mtu 1500
veth-peer-name veth_int2ext
vrf vrf_external
auto veth_int2ext
iface veth_int2ext
link-type veth
mtu 1500
veth-peer-name veth_ext2int
```
Currently both interfaces will resolve the pair as a dependency. I'm unsure if this is the best corse of action. The idea is to make sure the regardless which interface is ifup'd that the other one if configured as well.
=> Add support for veth interface pairs

executor-scripts/linux/static, libifupdown/lifecycle.c, libifupdown/version.c, tests/linux/static_test
Gather all IP addresses and gateways and expose them as `IF_ADDRESSES` and
`IF_GATEWAYS` environment variables to executors. This eliminates the need
to run ifquery from execuctors which would have to parse the config file
again on every run.
=> Expose all adresses and gateways as environment variables

executor-scripts/linux/batman
Setting options of B.A.T.M.A.N. adv. hardifs depends on #12 to be revisited.
=> Generalize B.A.T.M.A.N. .adv. option handling

cmd/ifquery.c, libifupdown/dict.c, libifupdown/dict.h, libifupdown/interface.c, libifupdown/interface.h, libifupdown/lifecycle.c
When setting up an interface like
```
iface eth0
address 192.0.2.1
netmask 255.255.255.128
```
ifupdown-ng did not configure this interface correctly since #100 was merged as the netmask was not given to the executor. The PR fixes that behavirour and computes a CIDR netmask if necessary.
=> Always convert netmasks to CIDR when configuring interfaces

cmd/ifquery.c, cmd/ifupdown.c, doc/interfaces.scd, libifupdown/interface-file.c, libifupdown/interface-file.h
=> refactor config file management

dist/ifupdown-ng.conf.example, doc/ADMIN-GUIDE.md, libifupdown/config-file.c, libifupdown/config-file.h, libifupdown/interface-file.c, libifupdown/interface.c
This improves upon the `hostname $(hostname)` stuff by simply learning the hostname at interface creation time using uname(2). Closes #74.
=> dhcp hostname normalization

cmd/ifquery.c, cmd/ifupdown.c, libifupdown/interface-file.c, libifupdown/interface.c, libifupdown/interface.h, libifupdown/lifecycle.c, libifupdown/state.c, libifupdown/state.h
To protect against interfaces being deconfigured due to being a dependency, we mark `auto` and explicit (`ifup wlan0` for example) interfaces as such.
This resolves #115.
=> guard auto and explicitly configured interfaces from inappropriate deconfiguration

cmd/multicall.c, tests/Kyuafile, tests/multicall_test
=> multicall: fix inappropriate use of getopt in the multicall stub

libifupdown/interface-file.c, libifupdown/interface.c, libifupdown/interface.h, tests/fixtures/stanza-merging.interfaces, tests/ifquery_test
By adding and using `lif_interface_finalize()`, we can rewrite stanza address properties to use CIDR notation as they are processed.
Closes #131.
=> improve stanza merging by rewriting address properties as CIDR

executor-scripts/linux/dhcp
They are opt-args, not pop-tarts.
=> dhcp executor: Pass correct arguments to dhclient

executor-scripts/linux/static, tests/linux/static_test
This ensures we wind up with a clean slate for the interface or VRF when taking
interfaces/VRFs down.
Closes #149.
=> static: use ip addr|route flush instead of manually deleting matching routes

Makefile, doc/interfaces-tunnel.scd, doc/interfaces.scd, executor-scripts/linux/tunnel
- Add support for `tunnel-local-dev` to automatically determine the IP of the local tunnel endpoint
- Add `interfaces-tunnel` man page
- Add support for setting `[no]ignore-df` as well as  `[no]pmtudisc` options for tunnels
This could need another round of tests before this is merged. Kyua tests don't help much here as this relies on configured IP addresses and what `iproute2` allows to configured.
=> Brush up tunnels

doc/interfaces-vxlan.scd, executor-scripts/linux/vxlan, libifupdown/interface-file.c, tests/linux/vxlan_test
This commit adds support for configuring static PTMP overlays with VXLAN by
allowing to specify multiple IPs for »vxlan-peer-ips«.  If more than one IP
is given ifupdown-ng will set up additional FDB entries for all peer IPs and
the Linux Kernel will do ingres / head-end replication for BUM traffic.
For a cleaner naming schema and simliar names to commercial vendor CLIs the
options to specify unicast or multicast peers have been renamed and aliases
added for compatibility to previous versions of ifupdown-ng:
* »vxlan-remote-ip« now is named »vxlan-peer-ips«
* »vxlan-remote-group« now is called »vxlan-peer-group«
=> vxlan: Add support for PTMP setups and rename options to vxlan-peer-{ips,group}

executor-scripts/linux/wifi
When stopping wpa_supplicant, the code is supposed to check if a file named $PIDFILE exists and kill the process listed inside. Instead it was checking if a directory named $PIDFILE exists and because this was never the case, killing of the wpa_supplicant process would always silently fail.
This would, after a few invocations of the ifup command, leave the system with large number of running wpa_supplicant processes, all trying to take control of the same interface.
=> Fix a bug in the wifi executor script

Makefile
To support usrmerge installation in Yocto, make SBINDIR a variable which
can be overridden.
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
Signed-off-by: Alex Kiernan <alexk@zuma.ai>
=> build: Allow /sbin to be overridden for usrmerge

libifupdown/lifecycle.c
Without this patch, `handle_executors_for_phase` would always return true,
even if the executor exited with a non-zero exit status. I noticed this
in conjunction with the dhcp executor were libifupdown would incorrectly
assume that the executor was executed successfully if no lease was
acquired. This caused ifupdown to get into a weird state where it
assumed that the interface was configured successfully even though it
wasn't, thus requiring an explicit `ifdown <interface>` before
it was possible to acquire a lease again with `ifup <interface>`.
=> libifupdown: check executor exit status in handle_executors_for_phase

cmd/ifctrstat-linux.c
This is to fix a build failure on Debian hurd-i386, see [buildd logs](https://buildd.debian.org/status/fetch.php?pkg=ifupdown-ng&arch=hurd-i386&ver=0.11.4%7Erc1-1&stamp=1643650932&raw=0)
Apparently PATH_MAX is not mandated by POSIX but rather "may" be defined. See https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html
=> Replace use of PATH_MAX with GNU asprintf

executor-scripts/linux/dhcp
This allows for successfully taking down an interface that doesn't use DHCP yet, but with `use dhcp` added in the meantime to /etc/network/interfaces
=> dhcp: ignore fails on stopping the dhcp client process

Makefile
This is a well known variable set by many Linux distributions (e.g. Alpine). Without this change, the ifupdown-ng build system does not pick up linker flags passed via LDFLAGS.
=> Makefile: Pick up LDFLAGS variable when linking multicall binary

executor-scripts/linux/link
This is one possible solution to the issue raised in https://github.com/ifupdown-ng/ifupdown-ng/pull/54#discussion_r922671069.
While not as perfect as the previous approach, this will work with Busybox's implementation of `ip`, which doesn't support the `-d` flag.
/cc @BarbarossaTM @kaniini
=> dummy: Verify the interface is virtual

executor-scripts/linux/link
Fixes https://github.com/ifupdown-ng/ifupdown-ng/issues/184.
A `dummy0` interface is automatically created when loading the `dummy` kernel module. This presents a problem should the kernel module be loaded as a result of a `ip link add dummy0 type dummy`, as the command fails due to `dummy0 `suddenly existing as a result of the integrated kernel module load:
```
$ ip link add dummy0 type dummy
ip: RTNETLINK answers: File exists
```
By loading the kernel module separately, the `dummy0` interface is detected thanks to the presence of `/sys/class/net/dummy0` and reused should `dummy0` be specified as the interface name with ifupdown-ng.
=> Load the dummy kernel module

cmd/ifupdown.c, libifupdown/lifecycle.c
Without this commit, all executors of a given phase will be executed
even if one of them fails. This commit adjusts handle_executors_for_phase
to stop execution if a single executor for a given phase exits with a
non-zero exit status.
This is a follow-up to 6f52157335aee39b6fc25a1dfb0a86dadd6b5c5d.
=> libifupdown: stop executor evaluation after an executor fails

libifupdown/interface-file.c
When using a read-only rootfs with a writable overlay for `/etc` the `d_type` from `readdir()` does not return `DT_REG` for files read from `/etc/network/interfaces.d/`. With `st_mode` from `stat()` we do not have this problem.
See also [readdir(3)](https://man7.org/linux/man-pages/man3/readdir.3.html):
> "Currently, only some filesystems (among them: Btrfs, ext2, ext3, and ext4)
>  have full support for returning the file type in d_type."
=> libifupdown: use stat() instead of relying on DT_REG

executor-scripts/linux/vrf
I notice that when I shutdown an interface which is part of a VRF, the script is not removing the interface from the VRF.
That leads sometimes to some issue if you want to reuse that interface for other purpose in global VRF. If you reconfigure the interface and try to rerun the ifup for that interface under global VRF which previously was under a VRF, you will notice that the interface is still have the master the prevoius VRF.
Normally if you shutdown an interface and is a physical one, not a virtual one, should go back to default VRF.
=> VRF shutdown fix

dist/debian/ifupdown-ng.networking.service
This PR is fixing the startup service for Systemd.
The service was created with ExecRestart which in systemd documentation doesn't exist!
Looks like for a period of time the service worked with this error, but in Debian Trixie the service stops to work anymore.
It fails with **Unknown key name 'ExecRestart' in section 'Service'**
Please push this PR ASAP because can cause no network on Linux starts.
=> Fix Debian systemd service - URGENT

executor-scripts/linux/vrf
Fix the exit codes for VRF executor. In 0.12.1 the forked executor must exits with 0 to be able for ifupdown to continue with the rest of the configuration.
This fixes #211 bug.
In case of using without this fix and ifupdown-ng is used in a router, this could lead to unbootable system!
This fix should be treated as critical.
=> Fix VRF executor exit code for ifupdown-ng 0.12.1 - CRITICAL

libifupdown/lifecycle.c
Some shells do not set the default PATH when called with an empty environment. So, reset the PATH to sane defaults before calling the executors.
Fixes #197
=> libifupdown/lifecycle.c: set PATH for executors

executor-scripts/linux/static
Add the "onlink" next-hop option to the default route. This is required for situations like some VPS/Cloud Providers where they provide a /32 IPv4 address or a /128 IPv6 address and obviously the router to use as the gateway for the default route is not in the same subnet.
Debian's ifupdown package has been adding the "onlink" option for the past 7 years.
https://salsa.debian.org/debian/ifupdown/-/commit/8b7bca9597d2f75670b182f0fc149cdbaec3544c
=> static executor: add "onlink" option for default route

executor-scripts/linux/link
Fix link executor for tests in case on compilation machine interface in case an interface with name "servers" exist
In case is in test mode, MOCK variable is set then we should skip interface presence check in system.
On my test machine I had a VRF named "servers" and is the same name for the VLAN 123 test in vlan_explicit_create.
=> Fix link executor test in case there is an interface named "servers" on machine

Makefile
Had to rewrite rules for docs generation so they won't trigger on each 'make docs' invocation.
Closes #14
=> Introduce BUILDDIR variable for build artifacts directory

Makefile, doc/interfaces-dhcp.scd, executor-scripts/linux/dhcp, tests/linux/dhcp_test
All DHCP clients now support:
dhcp-opts STRING
dhcp-script PATH
dhcpcd and dhclient (but not udhcpc) now support:
dhcp-config PATH
dhcpcd and udhcpc (but not dhclient) now support:
dhcp-hostname STRING
dhcp-client_id HEX
dhcp-vendor STRING
dhcp-leasetime INT
Add related document in interfaces-dhcp
Extend tests to include MOCK evaluation of these updated options for all 3 clients
--
Resolves a bug where dhcpcd uses the -i flag for both client_id and vendor; client_id now uses -I
Improves busybox compatiblity for udhcpc by using -x 0x3d instead of -c for client_id
Resolves ifupdown-ng issue #177
=> Support consistent options for all DHCP implementations (where possible)

executor-scripts/linux/bridge
Enabling bridge-stp according to the documentation doesn't work when iproute2 is used. The yesno function only detects the boolean types which don't include 'on'/'off' as used by brctl.
Add on & ON to the valid values for boolean types.
=> bridge executor: allow 'bridge-stp on' with iproute2

executor-scripts/linux/wifi
wpa_supplicant-2.11 changed wpa_passphrase to require a tty.
The only problem i see is that password may now show in audit logs, if that's a problem we can generate config manually with heredoc i guess.
=> wifi: pass psk as argument to wpa_passphrase

Makefile
Relative symlinks are (in my opinion) more robust even when SBINDIR is moved after installation or the filesystem isn't mounted on /.
=> Use relative symlinks for multicall binary

doc/interfaces.scd
Documents commit 11640bdd5e "Support including 'source' files by pattern for ifupdown compat".
=> doc: Document pattern support for 'source' keyword

executor-scripts/linux/bridge
When setting the ``bridge-hw`` option the like in ...
```
auto br0
iface br0
use bridge
use dhcp
bridge-hw 00:25:90:2b:30:de
bridge-ports enp5s0f0
bridge-fd 0
bridge-stp off
```
... the bridge executer in the pre-up phase changed the hardware address of the bridge port, not the bridge itself:
```
ifupdown: br0: attempting to run bridge executor for phase pre-up                                                                                                                                                                             
/usr/libexec/ifupdown-ng/bridge                            
+ PORTS=enp5s0f0                                                                                                       
+ [ enp5s0f0  ]                                            
... …
```
=> bridge executor: change implementation of 'bridge-hw'

doc/interfaces-bridge.scd, executor-scripts/linux/bridge
Every bridge sets a default pvid of 1 which gets assigned to all ports by default. Allow setting/disabling this from the interfaces file.
Fixes #258
=> bridge: Add option to set vlan_default_pvid

executor-scripts/linux/ipv6-ra
When forwarding is enabled on an interface, Linux only accepts router advertisements when accept_ra is set to 2.
=> executor/ipv6-ra: set accept_ra=2 if forwarding is enabled

cmd/pretty-print-iface.c, doc/interfaces.scd, libifupdown/interface-file.c, libifupdown/interface.h
Add support for interface defaults, a special template which is inherited by all configuration objects which are not explicitly configured with the new `no-defaults` option.
This provides some syntax sugar around the new `defaults` keyword in interfaces(5).
=> interface defaults
