executor-scripts/linux/ppp
libifupdown/interface-file.c
tests/fixtures/ppp-legacy.interfaces
tests/fixtures/ppp.interfaces
tests/ifquery_test
tests/linux/Kyuafile
tests/linux/ppp_test

Implements ppp executor and compatibility with `iface ppp0 inet ppp` style declarations.

ppp executor

---

cmd/ifquery.c
cmd/ifupdown.c
libifupdown/interface-file.c
libifupdown/interface.c

rewrite of the interfaces(5) parser to be modular.  adds +3KB, but I think it is worth it because it's much cleaner.

interface config parser rewrite

---

executor-scripts/linux/link
executor-scripts/linux/static
libifupdown/dict.h
libifupdown/lifecycle.c
libifupdown/list.h
tests/fixtures/vlan-complex.interfaces
tests/ifquery_test
tests/linux/link_test

* default to metric=1 for static routes for cleanliness
* run executors backwards when taking links down

vlan and assorted fixes

---

Makefile
executor-scripts/linux/wireguard
tests/fixtures/wireguard.interfaces
tests/ifquery_test
tests/linux/Kyuafile
tests/linux/wireguard_test

wireguard executor implementation

---

executor-scripts/linux/batman

WIP: Add executor for managing B.A.T.M.A.N. adv. interfaces

---

Makefile
cmd/multicall.c
dist/ifupdown-ng.conf.example
libifupdown/config-file.c
libifupdown/config-file.h
libifupdown/config-parser.c
libifupdown/config-parser.h
libifupdown/libifupdown.h
libifupdown/lifecycle.c
libifupdown/tokenize.h

Adds an optional config file.  Syntax rules are the same as ifupdown2's config file syntax.
Also add the ability to disable addon scripts.  Closes #77.

config file support

---

executor-scripts/linux/link

* Don't try do down an interface which has vanished
* Really don't try to re-create an existing dummy interface

Clean up link executor

---

dist/debian/ifupdown-ng.networking.service
dist/debian/networking
dist/debian/networking.default

* Systemd unit file for networking.service
* Small wrapper script called by networking.service
* Defaults file for networking.service

Add files required for Debian packaging

---

doc/interfaces.scd
executor-scripts/linux/static
libifupdown/interface-file.c
tests/fixtures/static-eth0-ptp.interfaces
tests/linux/static_test

static executor: Add support for IPv4 'pointopoint' addresses.

---

Makefile
doc/interfaces-batman.scd
doc/interfaces-bridge.scd
doc/interfaces-ppp.scd
doc/interfaces-vrf.scd
doc/interfaces-wireguard.scd
doc/interfaces.scd

Man pages for B.A.T.M.A.N. adv., bridges, ethtool, VRFs

---

cmd/ifquery.c
dist/openrc/networking.confd
dist/openrc/networking.initd
doc/ifquery.scd

Based on the current Alpine `/etc/init.d/networking`.

openrc init script

---

Makefile
cmd/ifupdown.c
libifupdown/compat.c
libifupdown/compat.h
libifupdown/libifupdown.h

This is only the framework for mangling the configuration with function which will be implemented as needed. The intention is add a config option for each compat function introduced. The first one to come is for bridge-vlan stuff.

Introduce compatibility layer framework

---

Makefile
cmd/ifquery.c
dist/ifupdown-ng.conf.example
doc/ADMIN-GUIDE.md
doc/ifdown.scd
doc/ifup.scd
doc/ifupdown-ng.conf.scd
doc/interfaces-bridge.scd
doc/interfaces.scd
executor-scripts/linux/bridge
libifupdown/compat.c
libifupdown/config-file.c
libifupdown/config-file.h
libifupdown/interface-file.c

vlan aware bridging

---

Makefile
doc/interfaces-wifi.scd
doc/interfaces.scd
executor-scripts/linux/wifi

Adds support for configuring connections to wifi networks, using either wpa_supplicant or iwconfig as appropriate.  Support for iwd could be added later.

wifi executor

---

Makefile

Makefile: Install all executors, sort them alphabetically

---

.gitignore
executor-scripts/linux/tunnel
libifupdown/interface-file.c
tests/linux/tunnel_test

Currently waiting for user confirmation this fixes the problem

tunnel executor: Make sure mode/type is 1st parameter

---

executor-scripts/linux/bond
tests/linux/Kyuafile
tests/linux/bond_test

Add test for bond executor

---

executor-scripts/linux/tunnel
tests/linux/tunnel_test

Add support for gretap tunnels over IPv6 networks

---

doc/interfaces.scd

* Interface file is case-sensitive and all lower-case
* Clariry netmask handling and fallback

doc: Clarify some interface file properties

---

cmd/multicall-exec-options.c
doc/ifdown.scd
doc/ifparse.scd
doc/ifquery.scd
doc/ifup.scd
libifupdown/execute.c
libifupdown/execute.h
libifupdown/lifecycle.c

implement executor timeouts

---

Makefile
doc/interfaces-wireguard-quick.scd
doc/interfaces-wireguard.scd
executor-scripts/linux/wireguard-quick

merge wg-quick stuff

---

executor-scripts/stub/bridge

stub: check for bridge package on alpine

---

executor-scripts/linux/vrf
tests/linux/vrf_test

Hi,
I recreated this pull request from a branch.
I deleted the ip rule in tests.

Fix vrf ip rule for kernels equal or greater than 4.8

---

executor-scripts/linux/gre

gre: Rework busybox logic and white space cleanup

---

Makefile
doc/interfaces-cake-ingress.scd
doc/interfaces-cake.scd
executor-scripts/linux/cake
executor-scripts/linux/cake-ingress
tests/linux/Kyuafile
tests/linux/cake-ingress_test
tests/linux/cake_test

Supports all options for CAKE
Supports creation of an IFB interface for ingress shaping
Includes man pages and MOCK tests

CAKE shaping using the interfaces file format

---

libifupdown/interface-file.c

Debian's default installation (using debian-installer) ends up with a source line like `source /etc/network/interfaces.d/*` in /etc/network/interfaces so it's important to support this ifupdown feature for compatibility.

Support including 'source' files by pattern for ifupdown compat

---

dist/openrc/networking.confd
dist/openrc/networking.initd

See commit messages for details.
I don't feel strongly about the last commit, it can freely be left out if it's found to be undesirable

dist/openrc: Improve service script

---

executor-scripts/linux/link

See commit messages for details
Prerequisite for a separate PR implementing very basic network namespace support, split to ease review
This was fun. I'd be interested in doing something similar for other executors too, if there's interest in reviewing the changes?

executor/link: Misc cleanup
